name: price-alert-dev
services:
  web:
    build:
      target: development
    volumes:
      - type: bind
        source: ../../web/src
        target: /app/src
  reverse-proxy:
    build:
      context: ../nginx/
      dockerfile: ../docker/nginx.Dockerfile
