services:
  web:
    container_name: web-dev
    image: price-alert-web-dev
    hostname: web
    build:
      target: development
    volumes:
      - type: bind
        source: ../../web/src
        target: /app/src
