name: price-alert
services:
  web-test:
    container_name: web-test
    build:
      context: ../web/
      dockerfile: ../docker/web.Dockerfile
      target: test
    profiles:
      - test
  api-test:
    container_name: api-test
    build:
      context: ../backend/PriceAlert
      dockerfile: ../../docker/api.Dockerfile
      target: test
    profiles:
      - test
  web:
    container_name: web
    build:
      context: ../web/
      dockerfile: ../docker/web.Dockerfile
      target: production
    profiles:
      - production
  api:
    container_name: api
    build:
      context: ../backend/PriceAlert/
      dockerfile: ../../docker/api.Dockerfile
      target: production
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
    profiles:
      - production
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ../nginx/
      dockerfile: ../docker/nginx.Dockerfile
    ports:
      - app_protocol: http
        target: 4000
        published: 80
    profiles:
      - production
