#cloud-config

cloud_config_modules:
  - runcmd

cloud_final_modules:
  - scripts-user

write_files:
  - path: /scripts/install-docker-engine.sh
    permissions: 0744
    owner: root
    content: |
      #!/usr/bin/env bash
      sudo apt-get update
      sudo apt-get install --assume-yes --quiet ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install --assume-yes docker-ce

runcmd:
  - bash /scripts/install-docker-engine.sh
