#cloud-config

cloud_config_modules:
  - runcmd

cloud_final_modules:
  - scripts-user

write_files:
  - path: /scripts/install-docker-engine.sh
    permissions: '0744'
    owner: root
    content: |
      #!/usr/bin/env bash
      sudo apt-get update
      sudo apt-get install --assume-yes ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install --assume-yes docker-ce

  - path: /scripts/deploy-application.sh
    permissions: '0744'
    owner: root
    content: |
      # create folder
      mkdir /app

      # download docker-compose.yaml
      wget --output-document=/app/docker-compose.yaml https://raw.githubusercontent.com/samuelko123/price-alert/refs/heads/main/infra/docker/docker-compose.yaml

      # pull docker images
      docker compose --file /app/docker-compose.yaml --profile production pull

      # run docker compose
      docker compose --file /app/docker-compose.yaml --profile production up --detach --remove-orphans

runcmd:
  - bash /scripts/install-docker-engine.sh
  - bash /scripts/deploy-application.sh
