name: Pull Request Merged

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "./.vscode"
      - ".gitignore"
      - "*.md"
      - "LICENSE"
jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit
