name: Pull Request Merged

on:
  push:
    branches:
      - "main"

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit

  publish-docker-images:
    name: Publish Docker Images
    uses: ./.github/workflows/publish-docker-images.yaml
    secrets: inherit
    needs:
      - run-unit-tests

  trigger-deployment:
    name: Trigger Deployment
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    needs:
      - publish-docker-images
