name: Pull Request Checks

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "./.vscode"
      - ".gitignore"
      - "*.md"
      - "LICENSE"
jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit
