name: Pull Request Checks

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit

  trigger-deployment:
    name: Trigger Deployment
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
