name: Pull Request Checks

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "./.vscode"
      - ".gitignore"
      - "*.md"
      - "LICENSE"
  jobs:
    run-unit-tests:
      uses: ./.github/workflows/run-unit-tests.yaml
      secrets: inherit
