name: Pull Request Checks

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "LICENCE"
      - "README.md"
      - "./readme"

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit
