name: Unit Tests

on:
  workflow-call:

jobs:
  web-test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: |
          docker compose --file ./docker/docker-compose.yaml up web-test --exit-code-from web-test --build --remove-orphans

  api-test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: |
          docker compose --file ./docker/docker-compose.yaml up api-test --exit-code-from api-test --build --remove-orphans
